import type { DataType } from '@/app/reports/utils/columns';

export const mockReportsData: DataType[] = [
  // Офис А (20 сотрудников)
  {
    id: 1,
    office: 'Офис А',
    name: 'Иван Петров',
    position: 'младший продавец',
    plan: 200,
    sold: 150,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 2,
    office: 'Офис А',
    name: 'Мария Иванова',
    position: 'продавец',
    plan: 180,
    sold: 160,
    percent: 88.9,
    rating: 'отлично',
  },
  {
    id: 3,
    office: 'Офис А',
    name: 'Сергей Сидоров',
    position: 'старший продавец',
    plan: 250,
    sold: 230,
    percent: 92,
    rating: 'отлично',
  },
  {
    id: 4,
    office: 'Офис А',
    name: 'Елена Кузнецова',
    position: 'продавец',
    plan: 150,
    sold: 70,
    percent: 46.7,
    rating: 'удовлетворительно',
  },
  {
    id: 5,
    office: 'Офис А',
    name: 'Алексей Смирнов',
    position: 'младший продавец',
    plan: 120,
    sold: 30,
    percent: 25,
    rating: 'неудовлетворительно',
  },
  {
    id: 6,
    office: 'Офис А',
    name: 'Наталья Федорова',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 7,
    office: 'Офис А',
    name: 'Дмитрий Попов',
    position: 'старший продавец',
    plan: 300,
    sold: 280,
    percent: 93.3,
    rating: 'отлично',
  },
  {
    id: 8,
    office: 'Офис А',
    name: 'Ольга Морозова',
    position: 'младший продавец',
    plan: 100,
    sold: 50,
    percent: 50,
    rating: 'удовлетворительно',
  },
  {
    id: 9,
    office: 'Офис А',
    name: 'Андрей Соколов',
    position: 'продавец',
    plan: 180,
    sold: 100,
    percent: 55.6,
    rating: 'удовлетворительно',
  },
  {
    id: 10,
    office: 'Офис А',
    name: 'Светлана Лебедева',
    position: 'старший продавец',
    plan: 220,
    sold: 200,
    percent: 90.9,
    rating: 'отлично',
  },
  {
    id: 11,
    office: 'Офис А',
    name: 'Игорь Петров',
    position: 'младший продавец',
    plan: 130,
    sold: 60,
    percent: 46.2,
    rating: 'удовлетворительно',
  },
  {
    id: 12,
    office: 'Офис А',
    name: 'Татьяна Иванова',
    position: 'продавец',
    plan: 210,
    sold: 190,
    percent: 90.5,
    rating: 'отлично',
  },
  {
    id: 13,
    office: 'Офис А',
    name: 'Владимир Сидоров',
    position: 'старший продавец',
    plan: 250,
    sold: 240,
    percent: 96,
    rating: 'отлично',
  },
  {
    id: 14,
    office: 'Офис А',
    name: 'Ирина Кузнецова',
    position: 'продавец',
    plan: 160,
    sold: 120,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 15,
    office: 'Офис А',
    name: 'Константин Смирнов',
    position: 'младший продавец',
    plan: 110,
    sold: 40,
    percent: 36.4,
    rating: 'неудовлетворительно',
  },
  {
    id: 16,
    office: 'Офис А',
    name: 'Юлия Федорова',
    position: 'продавец',
    plan: 190,
    sold: 170,
    percent: 89.5,
    rating: 'отлично',
  },
  {
    id: 17,
    office: 'Офис А',
    name: 'Павел Попов',
    position: 'старший продавец',
    plan: 270,
    sold: 260,
    percent: 96.3,
    rating: 'отлично',
  },
  {
    id: 18,
    office: 'Офис А',
    name: 'Алена Морозова',
    position: 'младший продавец',
    plan: 140,
    sold: 100,
    percent: 71.4,
    rating: 'хорошо',
  },
  {
    id: 19,
    office: 'Офис А',
    name: 'Николай Соколов',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 20,
    office: 'Офис А',
    name: 'Марина Лебедева',
    position: 'старший продавец',
    plan: 250,
    sold: 220,
    percent: 88,
    rating: 'отлично',
  },

  // Офис Б (20 сотрудников)
  {
    id: 21,
    office: 'Офис Б',
    name: 'Алексей Петров',
    position: 'младший продавец',
    plan: 150,
    sold: 60,
    percent: 40,
    rating: 'удовлетворительно',
  },
  {
    id: 22,
    office: 'Офис Б',
    name: 'Мария Смирнова',
    position: 'продавец',
    plan: 200,
    sold: 150,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 23,
    office: 'Офис Б',
    name: 'Сергей Иванов',
    position: 'старший продавец',
    plan: 300,
    sold: 270,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 24,
    office: 'Офис Б',
    name: 'Елена Федорова',
    position: 'продавец',
    plan: 180,
    sold: 100,
    percent: 55.6,
    rating: 'удовлетворительно',
  },
  {
    id: 25,
    office: 'Офис Б',
    name: 'Александр Попов',
    position: 'младший продавец',
    plan: 120,
    sold: 40,
    percent: 33.3,
    rating: 'неудовлетворительно',
  },
  {
    id: 26,
    office: 'Офис Б',
    name: 'Наталья Кузнецова',
    position: 'продавец',
    plan: 200,
    sold: 190,
    percent: 95,
    rating: 'отлично',
  },
  {
    id: 27,
    office: 'Офис Б',
    name: 'Дмитрий Соколов',
    position: 'старший продавец',
    plan: 250,
    sold: 230,
    percent: 92,
    rating: 'отлично',
  },
  {
    id: 28,
    office: 'Офис Б',
    name: 'Ольга Лебедева',
    position: 'младший продавец',
    plan: 100,
    sold: 50,
    percent: 50,
    rating: 'удовлетворительно',
  },
  {
    id: 29,
    office: 'Офис Б',
    name: 'Андрей Петров',
    position: 'продавец',
    plan: 180,
    sold: 160,
    percent: 88.9,
    rating: 'отлично',
  },
  {
    id: 30,
    office: 'Офис Б',
    name: 'Светлана Смирнова',
    position: 'старший продавец',
    plan: 220,
    sold: 200,
    percent: 90.9,
    rating: 'отлично',
  },
  {
    id: 31,
    office: 'Офис Б',
    name: 'Игорь Иванов',
    position: 'младший продавец',
    plan: 130,
    sold: 60,
    percent: 46.2,
    rating: 'удовлетворительно',
  },
  {
    id: 32,
    office: 'Офис Б',
    name: 'Татьяна Федорова',
    position: 'продавец',
    plan: 210,
    sold: 190,
    percent: 90.5,
    rating: 'отлично',
  },
  {
    id: 33,
    office: 'Офис Б',
    name: 'Владимир Попов',
    position: 'старший продавец',
    plan: 250,
    sold: 240,
    percent: 96,
    rating: 'отлично',
  },
  {
    id: 34,
    office: 'Офис Б',
    name: 'Ирина Кузнецова',
    position: 'продавец',
    plan: 160,
    sold: 120,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 35,
    office: 'Офис Б',
    name: 'Константин Соколов',
    position: 'младший продавец',
    plan: 110,
    sold: 40,
    percent: 36.4,
    rating: 'неудовлетворительно',
  },
  {
    id: 36,
    office: 'Офис Б',
    name: 'Юлия Лебедева',
    position: 'продавец',
    plan: 190,
    sold: 170,
    percent: 89.5,
    rating: 'отлично',
  },
  {
    id: 37,
    office: 'Офис Б',
    name: 'Павел Петров',
    position: 'старший продавец',
    plan: 270,
    sold: 260,
    percent: 96.3,
    rating: 'отлично',
  },
  {
    id: 38,
    office: 'Офис Б',
    name: 'Алена Смирнова',
    position: 'младший продавец',
    plan: 140,
    sold: 100,
    percent: 71.4,
    rating: 'хорошо',
  },
  {
    id: 39,
    office: 'Офис Б',
    name: 'Николай Иванов',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 40,
    office: 'Офис Б',
    name: 'Марина Федорова',
    position: 'старший продавец',
    plan: 250,
    sold: 220,
    percent: 88,
    rating: 'отлично',
  },

  // Офис В (20 сотрудников)
  {
    id: 41,
    office: 'Офис В',
    name: 'Иван Смирнов',
    position: 'младший продавец',
    plan: 160,
    sold: 80,
    percent: 50,
    rating: 'удовлетворительно',
  },
  {
    id: 42,
    office: 'Офис В',
    name: 'Мария Попова',
    position: 'продавец',
    plan: 200,
    sold: 190,
    percent: 95,
    rating: 'отлично',
  },
  {
    id: 43,
    office: 'Офис В',
    name: 'Сергей Федоров',
    position: 'старший продавец',
    plan: 250,
    sold: 230,
    percent: 92,
    rating: 'отлично',
  },
  {
    id: 44,
    office: 'Офис В',
    name: 'Елена Петрова',
    position: 'продавец',
    plan: 180,
    sold: 120,
    percent: 66.7,
    rating: 'хорошо',
  },
  {
    id: 45,
    office: 'Офис В',
    name: 'Алексей Иванов',
    position: 'младший продавец',
    plan: 130,
    sold: 50,
    percent: 38.5,
    rating: 'неудовлетворительно',
  },
  {
    id: 46,
    office: 'Офис В',
    name: 'Наталья Сидорова',
    position: 'продавец',
    plan: 200,
    sold: 170,
    percent: 85,
    rating: 'отлично',
  },
  {
    id: 47,
    office: 'Офис В',
    name: 'Дмитрий Кузнецов',
    position: 'старший продавец',
    plan: 300,
    sold: 280,
    percent: 93.3,
    rating: 'отлично',
  },
  {
    id: 48,
    office: 'Офис В',
    name: 'Ольга Смирнова',
    position: 'младший продавец',
    plan: 100,
    sold: 40,
    percent: 40,
    rating: 'удовлетворительно',
  },
  {
    id: 49,
    office: 'Офис В',
    name: 'Андрей Попов',
    position: 'продавец',
    plan: 180,
    sold: 160,
    percent: 88.9,
    rating: 'отлично',
  },
  {
    id: 50,
    office: 'Офис В',
    name: 'Светлана Федорова',
    position: 'старший продавец',
    plan: 220,
    sold: 200,
    percent: 90.9,
    rating: 'отлично',
  },
  {
    id: 51,
    office: 'Офис В',
    name: 'Игорь Петров',
    position: 'младший продавец',
    plan: 130,
    sold: 60,
    percent: 46.2,
    rating: 'удовлетворительно',
  },
  {
    id: 52,
    office: 'Офис В',
    name: 'Татьяна Иванова',
    position: 'продавец',
    plan: 210,
    sold: 190,
    percent: 90.5,
    rating: 'отлично',
  },
  {
    id: 53,
    office: 'Офис В',
    name: 'Владимир Сидоров',
    position: 'старший продавец',
    plan: 250,
    sold: 240,
    percent: 96,
    rating: 'отлично',
  },
  {
    id: 54,
    office: 'Офис В',
    name: 'Ирина Кузнецова',
    position: 'продавец',
    plan: 160,
    sold: 120,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 55,
    office: 'Офис В',
    name: 'Константин Смирнов',
    position: 'младший продавец',
    plan: 110,
    sold: 40,
    percent: 36.4,
    rating: 'неудовлетворительно',
  },
  {
    id: 56,
    office: 'Офис В',
    name: 'Юлия Федорова',
    position: 'продавец',
    plan: 190,
    sold: 170,
    percent: 89.5,
    rating: 'отлично',
  },
  {
    id: 57,
    office: 'Офис В',
    name: 'Павел Попов',
    position: 'старший продавец',
    plan: 270,
    sold: 260,
    percent: 96.3,
    rating: 'отлично',
  },
  {
    id: 58,
    office: 'Офис В',
    name: 'Алена Морозова',
    position: 'младший продавец',
    plan: 140,
    sold: 100,
    percent: 71.4,
    rating: 'хорошо',
  },
  {
    id: 59,
    office: 'Офис В',
    name: 'Николай Соколов',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 60,
    office: 'Офис В',
    name: 'Марина Лебедева',
    position: 'старший продавец',
    plan: 250,
    sold: 220,
    percent: 88,
    rating: 'отлично',
  },

  // Офис Г (20 сотрудников)
  {
    id: 61,
    office: 'Офис Г',
    name: 'Иван Петров',
    position: 'младший продавец',
    plan: 200,
    sold: 150,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 62,
    office: 'Офис Г',
    name: 'Мария Иванова',
    position: 'продавец',
    plan: 180,
    sold: 160,
    percent: 88.9,
    rating: 'отлично',
  },
  {
    id: 63,
    office: 'Офис Г',
    name: 'Сергей Сидоров',
    position: 'старший продавец',
    plan: 250,
    sold: 230,
    percent: 92,
    rating: 'отлично',
  },
  {
    id: 64,
    office: 'Офис Г',
    name: 'Елена Кузнецова',
    position: 'продавец',
    plan: 150,
    sold: 70,
    percent: 46.7,
    rating: 'удовлетворительно',
  },
  {
    id: 65,
    office: 'Офис Г',
    name: 'Алексей Смирнов',
    position: 'младший продавец',
    plan: 120,
    sold: 30,
    percent: 25,
    rating: 'неудовлетворительно',
  },
  {
    id: 66,
    office: 'Офис Г',
    name: 'Наталья Федорова',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 67,
    office: 'Офис Г',
    name: 'Дмитрий Попов',
    position: 'старший продавец',
    plan: 300,
    sold: 280,
    percent: 93.3,
    rating: 'отлично',
  },
  {
    id: 68,
    office: 'Офис Г',
    name: 'Ольга Морозова',
    position: 'младший продавец',
    plan: 100,
    sold: 50,
    percent: 50,
    rating: 'удовлетворительно',
  },
  {
    id: 69,
    office: 'Офис Г',
    name: 'Андрей Соколов',
    position: 'продавец',
    plan: 180,
    sold: 100,
    percent: 55.6,
    rating: 'удовлетворительно',
  },
  {
    id: 70,
    office: 'Офис Г',
    name: 'Светлана Лебедева',
    position: 'старший продавец',
    plan: 220,
    sold: 200,
    percent: 90.9,
    rating: 'отлично',
  },
  {
    id: 71,
    office: 'Офис Г',
    name: 'Игорь Петров',
    position: 'младший продавец',
    plan: 130,
    sold: 60,
    percent: 46.2,
    rating: 'удовлетворительно',
  },
  {
    id: 72,
    office: 'Офис Г',
    name: 'Татьяна Иванова',
    position: 'продавец',
    plan: 210,
    sold: 190,
    percent: 90.5,
    rating: 'отлично',
  },
  {
    id: 73,
    office: 'Офис Г',
    name: 'Владимир Сидоров',
    position: 'старший продавец',
    plan: 250,
    sold: 240,
    percent: 96,
    rating: 'отлично',
  },
  {
    id: 74,
    office: 'Офис Г',
    name: 'Ирина Кузнецова',
    position: 'продавец',
    plan: 160,
    sold: 120,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 75,
    office: 'Офис Г',
    name: 'Константин Смирнов',
    position: 'младший продавец',
    plan: 110,
    sold: 40,
    percent: 36.4,
    rating: 'неудовлетворительно',
  },
  {
    id: 76,
    office: 'Офис Г',
    name: 'Юлия Федорова',
    position: 'продавец',
    plan: 190,
    sold: 170,
    percent: 89.5,
    rating: 'отлично',
  },
  {
    id: 77,
    office: 'Офис Г',
    name: 'Павел Попов',
    position: 'старший продавец',
    plan: 270,
    sold: 260,
    percent: 96.3,
    rating: 'отлично',
  },
  {
    id: 78,
    office: 'Офис Г',
    name: 'Алена Морозова',
    position: 'младший продавец',
    plan: 140,
    sold: 100,
    percent: 71.4,
    rating: 'хорошо',
  },
  {
    id: 79,
    office: 'Офис Г',
    name: 'Николай Соколов',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 80,
    office: 'Офис Г',
    name: 'Марина Лебедева',
    position: 'старший продавец',
    plan: 250,
    sold: 220,
    percent: 88,
    rating: 'отлично',
  },

  // Офис Д (20 сотрудников)
  {
    id: 81,
    office: 'Офис Д',
    name: 'Алексей Петров',
    position: 'младший продавец',
    plan: 150,
    sold: 60,
    percent: 40,
    rating: 'удовлетворительно',
  },
  {
    id: 82,
    office: 'Офис Д',
    name: 'Мария Смирнова',
    position: 'продавец',
    plan: 200,
    sold: 150,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 83,
    office: 'Офис Д',
    name: 'Сергей Иванов',
    position: 'старший продавец',
    plan: 300,
    sold: 270,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 84,
    office: 'Офис Д',
    name: 'Елена Федорова',
    position: 'продавец',
    plan: 180,
    sold: 100,
    percent: 55.6,
    rating: 'удовлетворительно',
  },
  {
    id: 85,
    office: 'Офис Д',
    name: 'Александр Попов',
    position: 'младший продавец',
    plan: 120,
    sold: 40,
    percent: 33.3,
    rating: 'неудовлетворительно',
  },
  {
    id: 86,
    office: 'Офис Д',
    name: 'Наталья Кузнецова',
    position: 'продавец',
    plan: 200,
    sold: 190,
    percent: 95,
    rating: 'отлично',
  },
  {
    id: 87,
    office: 'Офис Д',
    name: 'Дмитрий Соколов',
    position: 'старший продавец',
    plan: 250,
    sold: 230,
    percent: 92,
    rating: 'отлично',
  },
  {
    id: 88,
    office: 'Офис Д',
    name: 'Ольга Лебедева',
    position: 'младший продавец',
    plan: 100,
    sold: 50,
    percent: 50,
    rating: 'удовлетворительно',
  },
  {
    id: 89,
    office: 'Офис Д',
    name: 'Андрей Петров',
    position: 'продавец',
    plan: 180,
    sold: 160,
    percent: 88.9,
    rating: 'отлично',
  },
  {
    id: 90,
    office: 'Офис Д',
    name: 'Светлана Смирнова',
    position: 'старший продавец',
    plan: 220,
    sold: 200,
    percent: 90.9,
    rating: 'отлично',
  },
  {
    id: 91,
    office: 'Офис Д',
    name: 'Игорь Иванов',
    position: 'младший продавец',
    plan: 130,
    sold: 60,
    percent: 46.2,
    rating: 'удовлетворительно',
  },
  {
    id: 92,
    office: 'Офис Д',
    name: 'Татьяна Федорова',
    position: 'продавец',
    plan: 210,
    sold: 190,
    percent: 90.5,
    rating: 'отлично',
  },
  {
    id: 93,
    office: 'Офис Д',
    name: 'Владимир Попов',
    position: 'старший продавец',
    plan: 250,
    sold: 240,
    percent: 96,
    rating: 'отлично',
  },
  {
    id: 94,
    office: 'Офис Д',
    name: 'Ирина Кузнецова',
    position: 'продавец',
    plan: 160,
    sold: 120,
    percent: 75,
    rating: 'хорошо',
  },
  {
    id: 95,
    office: 'Офис Д',
    name: 'Константин Соколов',
    position: 'младший продавец',
    plan: 110,
    sold: 40,
    percent: 36.4,
    rating: 'неудовлетворительно',
  },
  {
    id: 96,
    office: 'Офис Д',
    name: 'Юлия Лебедева',
    position: 'продавец',
    plan: 190,
    sold: 170,
    percent: 89.5,
    rating: 'отлично',
  },
  {
    id: 97,
    office: 'Офис Д',
    name: 'Павел Петров',
    position: 'старший продавец',
    plan: 270,
    sold: 260,
    percent: 96.3,
    rating: 'отлично',
  },
  {
    id: 98,
    office: 'Офис Д',
    name: 'Алена Смирнова',
    position: 'младший продавец',
    plan: 140,
    sold: 100,
    percent: 71.4,
    rating: 'хорошо',
  },
  {
    id: 99,
    office: 'Офис Д',
    name: 'Николай Иванов',
    position: 'продавец',
    plan: 200,
    sold: 180,
    percent: 90,
    rating: 'отлично',
  },
  {
    id: 100,
    office: 'Офис Д',
    name: 'Марина Федорова',
    position: 'старший продавец',
    plan: 250,
    sold: 220,
    percent: 88,
    rating: 'отлично',
  },
];
