export const configProviderTheme = {
  token: {
    colorPrimary: '#FFE0B2',
    colorPrimaryHover: '#FFE0B2',
    colorText: '#000000',
    colorTextHeading: '#001529',
  },
  components: {
    Layout: {
      colorBgLayout: '#ededed',
    },
    Menu: {
      itemHoverColor: '#40a9ff',
      itemSelectedColor: '#1677ff',
      itemSelectedBg: '#001529',
      darkItemSelectedBg: '#FFE0B2',
      darkItemSelectedColor: '#001529',
    },
    Button: {
      colorPrimary: '#001529',
      colorPrimaryHover: '#004E7C',
      colorPrimaryActive: '#004E7C',
      primaryColor: '#F5F3F0',
      primaryShadow: '#001529',
      borderRadius: 6,
      defaultBg: '#FFE0B2',
      defaultHoverBg: '#FFE0B2',
      defaultActiveBg: '#FFE0B2',
      defaultHoverColor: '#001529',
      defaultActiveColor: '#001529',
      defaultHoverBorderColor: '#001529',
      defaultActiveBorderColor: '#001529',
    },
    Input: {
      color: '#001529',
      colorPlaceholder: '#888888',
      backgroundColor: '#ffffff',
      borderRadius: 6,
      borderColor: '#d9d9d9',
      borderHoverColor: '#ddb26f',
      borderFocusColor: '#ddb26f',
    },
    Select: {
      colorText: '#001529',
      colorTextPlaceholder: '#888',
      colorBgContainer: '#ffffff',
      borderColor: '#ddb26f',
      hoverBorderColor: '#ddb26f',
      activeBorderColor: '#ddb26f',
      controlOutlineWidth: 0,
      optionSelectedBg: '#FFF3E0',
      optionActiveBg: '#FFE0B2',
      borderRadius: 6,
    },
    Table: {
      colorText: '#000000',
      colorHeaderText: '#000000',
      colorHeaderBg: '#f5f5f5',
      colorRowHover: '#f0f0f0',
      borderColor: '#d9d9d9',
      headerBg: '#001529',
      headerColor: '#f5f3f0',
    },
    Form: {
      labelColor: '#000000',
      labelFontSize: 14,
      controlPadding: '8px 12px',
      helpTextColor: '#ff4d4f',
    },
    Pagination: {
      itemActiveBg: '#FFE0B2',
      itemActiveColor: '#001529',
      itemActiveColorHover: '#001529',
      itemBg: '#001529',
      itemColor: '#F5F3F0',
      itemBorderWidth: 0,
    },
    Card: {
      headerFontSize: '20px',
    },
  },
};
